import React, { useState } from 'react';
import { TopicCard, type SnT2025Topic } from './TopicCard';
import { Badge } from '../compound/Badge';
import { motion } from 'framer-motion';

/**
 * 🎨 TopicCard Demo - Showcasing Compound Component Patterns
 * 
 * This demonstration uses REAL SnT2025 topic data from the actual
 * conference program to showcase the TopicCard's flexibility.
 */

// Real SnT2025 topic data from snt2025_program.json
const realSnT2025Topics: SnT2025Topic[] = [
  {
    code: "T3.1",
    title: "Seismic, Hydroacoustic and Infrasound Technologies and Applications",
    theme: "Theme 3. Monitoring and On-Site Inspection Technologies and Techniques",
    description: "Acquisition and forwarding of continuous and segmented data; data assimilation; design of sensor systems; advanced sensors",
    keywords: ["Acquisition", "forwarding", "continuous data", "segmented data", "data assimilation", "design", "sensor systems", "advanced sensors"],
    sessions: [
      {
        session_id: "O3.1",
        title: "O3.1 Seismic, Hydroacoustic and Infrasound Technologies and Applications",
        time: "15:30 - 17:05",
        venue: "Forum",
        speakers: ["Mr Christos Saragiotis", "Mr Ronan Le Bras"],
        session_type: "Oral"
      }
    ],
    speakers: ["Mr Christos Saragiotis", "Mr Ronan Le Bras"],
    sessionCount: 1,
    speakerCount: 2,
    sessionTypes: ["Oral"],
    venues: ["Forum"],
    relevance_score: 0.95,
    priority_level: "high",
    expertise_level: "expert"
  },
  {
    code: "T3.2",
    title: "Radionuclide Technologies and Applications",
    theme: "Theme 3. Monitoring and On-Site Inspection Technologies and Techniques",
    description: "Sampling and sample processing, data acquisition, particulate sample systems, gamma–gamma coincidence counting; new generation noble gas systems, radionuclide laboratories",
    keywords: ["Sampling", "sample processing", "data acquisition", "particulate sample systems", "gamma-gamma coincidence counting", "noble gas systems", "radionuclide laboratories"],
    sessions: [
      {
        session_id: "O3.2",
        title: "O3.2 Radionuclide Technologies and Applications",
        time: "15:30 - 17:05",
        venue: "Forum",
        speakers: ["Anders Ringbom", "Nikolaus Helmut Hermanspahn"],
        session_type: "Oral"
      }
    ],
    speakers: ["Anders Ringbom", "Nikolaus Helmut Hermanspahn"],
    sessionCount: 1,
    speakerCount: 2,
    sessionTypes: ["Oral"],
    venues: ["Forum"],
    relevance_score: 0.92,
    priority_level: "high",
    expertise_level: "expert"
  },
  {
    code: "T1.1",
    title: "The Atmosphere and its Dynamics",
    theme: "Theme 1. The Earth as a Complex System",
    description: "Acoustic propagation and attenuation; transport of radionuclides; global circulation; volcano-acoustics; climatology; meteorology; noise sources",
    keywords: ["Acoustic propagation", "attenuation", "transport of radionuclides", "global circulation", "volcano-acoustics", "climatology", "meteorology", "noise sources"],
    sessions: [
      {
        session_id: "O5.1-448",
        title: "The Volcanic Information System: Long-Range Infrasound Monitoring of Volcanic Eruptions",
        time: "14:15 - 14:30",
        venue: "Forum",
        speakers: ["Mr Rodrigo De Negri"],
        session_type: "Oral"
      }
    ],
    speakers: ["Mr Rodrigo De Negri"],
    sessionCount: 1,
    speakerCount: 1,
    sessionTypes: ["Oral"],
    venues: ["Forum"],
    relevance_score: 0.87,
    priority_level: "medium",
    expertise_level: "intermediate"
  },
  {
    code: "T2.1",
    title: "Characterization of Treaty-Relevant Events",
    theme: "Theme 2. Monitoring events and Nuclear Test Sites",
    description: "Announced tests; detection, understanding the full extent of signals that may be generated by a nuclear explosion; location in time and space, analysis, characterization of the source, discrimination, screening criteria, differentiating nuclear tests from other human-made or natural events",
    keywords: ["Announced tests", "detection", "nuclear explosion", "location", "analysis", "characterization", "discrimination", "screening criteria", "nuclear tests", "natural events"],
    sessions: [],
    speakers: [],
    sessionCount: 0,
    speakerCount: 0,
    sessionTypes: [],
    venues: [],
    relevance_score: 0.89,
    priority_level: "high",
    expertise_level: "expert"
  },
  {
    code: "T5.1",
    title: "Synergies with Global Challenges",
    theme: "Theme 5. CTBT Science and Technology in the Global Context",
    description: "Civil and scientific applications of IMS data; natural hazards early warning systems, disaster risk reduction, nuclear and radiological emergencies; climate change studies; sustainable development goals; international collaboration; vDEC projects",
    keywords: ["Civil applications", "scientific applications", "IMS data", "natural hazards", "early warning systems", "disaster risk reduction", "nuclear emergencies", "climate change", "sustainable development", "international collaboration", "vDEC projects"],
    sessions: [
      {
        session_id: "Ke04",
        title: "Keynote on the Impact of Long-Term Shifts in Environmental Conditions on Society",
        time: "15:30 - 16:00",
        venue: "Festsaal",
        speakers: [],
        session_type: "Keynote"
      }
    ],
    speakers: [],
    sessionCount: 1,
    speakerCount: 0,
    sessionTypes: ["Keynote"],
    venues: ["Festsaal"],
    relevance_score: 0.94,
    priority_level: "high",
    expertise_level: "beginner"
  }
];

/**
 * 🎯 TopicCard Layout Demonstrations
 * 
 * These examples show different ways to compose TopicCard
 * using the compound component pattern.
 */

export default function TopicCardDemo() {
  const [selectedLayout, setSelectedLayout] = useState<'default' | 'compact' | 'minimal' | 'custom'>('default');
  const [selectedTopic, setSelectedTopic] = useState(0);

  const currentTopic = realSnT2025Topics[selectedTopic];

  return (
    <div className="max-w-4xl mx-auto p-6 space-y-8">
      <div className="text-center">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">
          TopicCard Demo - SnT2025 Real Data
        </h1>
        <p className="text-gray-600">
          Voice-controlled kiosk components using actual CTBTO topic data
        </p>
      </div>

      {/* Layout Controls */}
      <div className="flex flex-wrap gap-3 justify-center">
        <Badge 
          variant={selectedLayout === 'default' ? 'default' : 'outline'}
          className="cursor-pointer"
          onClick={() => setSelectedLayout('default')}
        >
          Default Layout
        </Badge>
        <Badge 
          variant={selectedLayout === 'compact' ? 'default' : 'outline'}
          className="cursor-pointer"
          onClick={() => setSelectedLayout('compact')}
        >
          Compact Layout
        </Badge>
        <Badge 
          variant={selectedLayout === 'minimal' ? 'default' : 'outline'}
          className="cursor-pointer"
          onClick={() => setSelectedLayout('minimal')}
        >
          Minimal Layout
        </Badge>
        <Badge 
          variant={selectedLayout === 'custom' ? 'default' : 'outline'}
          className="cursor-pointer"
          onClick={() => setSelectedLayout('custom')}
        >
          Custom Layout
        </Badge>
      </div>

      {/* Topic Selector */}
      <div className="flex flex-wrap gap-2 justify-center">
        {realSnT2025Topics.map((topic, index) => (
          <Badge
            key={topic.code}
            variant={selectedTopic === index ? 'default' : 'outline'}
            className="cursor-pointer text-xs"
            onClick={() => setSelectedTopic(index)}
          >
            {topic.code}
          </Badge>
        ))}
      </div>

      {/* Card Display */}
      <motion.div
        layout
        className="bg-gray-50 p-6 rounded-lg"
      >
        {selectedLayout === 'default' && (
          <TopicCard topic={currentTopic}>
            <TopicCard.Header>
              <TopicCard.Title />
              <TopicCard.Meta />
            </TopicCard.Header>
            <TopicCard.Body>
              <TopicCard.Description />
              <TopicCard.Keywords />
              <TopicCard.Sessions maxSessions={3} />
              <TopicCard.Speakers maxSpeakers={4} />
              <TopicCard.Venues />
            </TopicCard.Body>
            <TopicCard.Footer />
          </TopicCard>
        )}

        {selectedLayout === 'compact' && (
          <TopicCard topic={currentTopic} compact>
            <TopicCard.Header>
              <TopicCard.Title />
              <TopicCard.Meta />
            </TopicCard.Header>
            <TopicCard.Body>
              <TopicCard.Description />
              <TopicCard.Keywords />
              <TopicCard.Sessions maxSessions={2} />
            </TopicCard.Body>
          </TopicCard>
        )}

        {selectedLayout === 'minimal' && (
          <TopicCard topic={currentTopic} compact>
            <TopicCard.Header>
              <TopicCard.Title />
              <TopicCard.Meta />
            </TopicCard.Header>
            <TopicCard.Body>
              <TopicCard.Keywords />
            </TopicCard.Body>
          </TopicCard>
        )}

        {selectedLayout === 'custom' && (
          <TopicCard topic={currentTopic}>
            <TopicCard.Header>
              <div className="flex justify-between items-start">
                <div className="flex-1">
                  <TopicCard.Title className="text-purple-900" />
                  <div className="mt-2 text-sm text-gray-500">
                    {currentTopic.expertise_level} level • {currentTopic.sessionCount} sessions
                  </div>
                </div>
                <Badge variant="secondary" className="ml-4">
                  {currentTopic.priority_level}
                </Badge>
              </div>
            </TopicCard.Header>
            <TopicCard.Body>
              <TopicCard.Keywords />
              <TopicCard.Description />
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-3">
                <div>
                  <TopicCard.Sessions maxSessions={2} />
                </div>
                <div>
                  <TopicCard.Speakers maxSpeakers={3} />
                  <div className="mt-3">
                    <TopicCard.Venues />
                  </div>
                </div>
              </div>
            </TopicCard.Body>
            <TopicCard.Footer>
              <div className="flex items-center justify-between text-sm">
                <span className="text-gray-500">
                  {currentTopic.theme}
                </span>
                {currentTopic.relevance_score && (
                  <span className="text-purple-600 font-medium">
                    {(currentTopic.relevance_score * 100).toFixed(0)}% relevance
                  </span>
                )}
              </div>
            </TopicCard.Footer>
          </TopicCard>
        )}
      </motion.div>

      {/* CTBTO Context Information */}
      <div className="bg-purple-50 p-6 rounded-lg">
        <h3 className="text-lg font-semibold text-purple-900 mb-3">
          🧬 CTBTO Topic Classification System
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
          <div>
            <h4 className="font-medium text-purple-800 mb-2">Theme Categories</h4>
            <ul className="space-y-1 text-purple-700">
              <li>• <strong>Theme 1:</strong> The Earth as a Complex System</li>
              <li>• <strong>Theme 2:</strong> Monitoring events and Nuclear Test Sites</li>
              <li>• <strong>Theme 3:</strong> Monitoring and On-Site Inspection Technologies</li>
              <li>• <strong>Theme 5:</strong> CTBT Science and Technology in Global Context</li>
            </ul>
          </div>
          <div>
            <h4 className="font-medium text-purple-800 mb-2">Topic Codes</h4>
            <ul className="space-y-1 text-purple-700">
              <li>• <strong>T1.1:</strong> Atmosphere and Dynamics</li>
              <li>• <strong>T2.1:</strong> Treaty-Relevant Events</li>
              <li>• <strong>T3.1:</strong> Seismic/Hydroacoustic/Infrasound Tech</li>
              <li>• <strong>T3.2:</strong> Radionuclide Technologies</li>
              <li>• <strong>T5.1:</strong> Synergies with Global Challenges</li>
            </ul>
          </div>
        </div>
      </div>

      {/* Voice-Only Design Principles */}
      <div className="bg-blue-50 p-6 rounded-lg">
        <h3 className="text-lg font-semibold text-blue-900 mb-3">
          🎨 Voice-Only Kiosk Design Principles
        </h3>
        <ul className="space-y-2 text-blue-800 text-sm">
          <li>• <strong>No hover states</strong> - All interactions are voice-controlled</li>
          <li>• <strong>High contrast text</strong> - WCAG AAA compliance (7:1 ratio)</li>
          <li>• <strong>Large touch targets</strong> - 44px minimum for accessibility</li>
          <li>• <strong>Clear visual hierarchy</strong> - Easy scanning at kiosk distance</li>
          <li>• <strong>Compound components</strong> - Flexible composition for different layouts</li>
          <li>• <strong>Real CTBTO data</strong> - Authentic scientific topic information</li>
          <li>• <strong>Keyword highlighting</strong> - Purple accent for technical terms</li>
        </ul>
      </div>
    </div>
  );
} 